import { PageGuidance } from "./types";

export const PAGE_GUIDANCE_MAP: Record<string, PageGuidance> = {
  "/app": {
    route: "/app",
    stageName: "Workspace Home & Overview",
    stageIndex: 1,
    totalStages: 7,
    description: "Central operational dashboard displaying role-specific summary metrics, active challenges, and system notifications.",
    previousStage: undefined,
    nextStage: "Review Queue / Problem Submission",
    whoUsesIt: "All platform stakeholders (Citizens, Nodal Officers, HEI Leads, Admins).",
    whatDecisionHappens: "Triaging focus and navigating to active work items.",
    whatEvidenceMatters: "Aggregate problem counts, status indicators, and unread notifications.",
    whatHappensNext: "Users navigate to specific workflow modules (Review, Challenges, Readiness).",
    whyThisStage: "Provides unified operational visibility into societal problem tracking and active governance tasks.",
  },
  "/app/review": {
    route: "/app/review",
    stageName: "Problem Intake & Triaging",
    stageIndex: 2,
    totalStages: 7,
    description: "Incoming queue of unreviewed societal problem reports requiring initial nodal verification.",
    previousStage: "Workspace Home",
    nextStage: "Problem Qualification",
    whoUsesIt: "Government Nodal Officers & Platform Administrators.",
    whatDecisionHappens: "Initial verification whether a report contains sufficient detail to proceed to formal qualification.",
    whatEvidenceMatters: "Submitted problem description, location boundaries, sector tags, and attached raw evidence.",
    whatHappensNext: "Selected challenges are forwarded to the Qualification Protocol.",
    whyThisStage: "Filters out spam, incomplete submissions, or duplicate reports before formal evaluation.",
  },
  "/app/qualification": {
    route: "/app/qualification",
    stageName: "Problem Qualification Protocol",
    stageIndex: 3,
    totalStages: 7,
    description: "Categorize problem statements into SERVICE, CLARIFY, RESEARCH_REVIEW, or INNOVATION_CHALLENGE.",
    previousStage: "Problem Intake & Triaging",
    nextStage: "Institutional Capability Matching",
    whoUsesIt: "Government Nodal Officers (AI assists; human authorizes).",
    whatDecisionHappens: "Formal determination of the appropriate resolution route for the problem.",
    whatEvidenceMatters: "Technical complexity, regulatory scope, municipal service boundaries, and AI clarification reports.",
    whatHappensNext: "INNOVATION_CHALLENGE items advance to HEI Matching; SERVICE items route to municipal operations.",
    whyThisStage: "Prevents wasteful innovation spending on routine municipal complaints that can be resolved via standard service delivery.",
  },
  "/app/hei-matching": {
    route: "/app/hei-matching",
    stageName: "Institutional Capability Matching",
    stageIndex: 4,
    totalStages: 7,
    description: "Algorithmic matching of qualified innovation challenges to academic research units and HEI labs.",
    previousStage: "Problem Qualification",
    nextStage: "Institutional Commitments",
    whoUsesIt: "Government Nodal Officers & HEI Research Leads.",
    whatDecisionHappens: "Selecting matched HEI candidates for formal partnership invitations.",
    whatEvidenceMatters: "HEI lab capacity metrics, faculty research specializations, past project track record, and algorithmic match scores.",
    whatHappensNext: "Matched HEIs are invited to submit formal institutional commitments.",
    whyThisStage: "Connects complex municipal challenges directly with validated university research capabilities.",
  },
  "/app/commitments": {
    route: "/app/commitments",
    stageName: "Institutional Commitment Intake",
    stageIndex: 5,
    totalStages: 7,
    description: "Formalization of binding academic and industry commitment contracts.",
    previousStage: "Institutional Capability Matching",
    nextStage: "Pilot Readiness Audit",
    whoUsesIt: "HEI Leads, Industry Partners, and Government Nodal Officers.",
    whatDecisionHappens: "Formal acceptance or withdrawal of resource commitments.",
    whatEvidenceMatters: "Signed agreement documents, allocated lab resources, budget commitments, and faculty lead designations.",
    whatHappensNext: "Active commitments are bound as dependencies for Pilot Readiness evaluation.",
    whyThisStage: "Establishes legal and operational accountability before field resources are deployed.",
  },
  "/app/readiness": {
    route: "/app/readiness",
    stageName: "Pilot Readiness & Decision Assurance",
    stageIndex: 6,
    totalStages: 7,
    description: "Multi-dimensional readiness scoring and cryptographic Decision Assurance audit receipt generation.",
    previousStage: "Institutional Commitments",
    nextStage: "Field Pilot Execution",
    whoUsesIt: "Government Nodal Officers, Audit Teams, and Evaluation Jury.",
    whatDecisionHappens: "Transitioning readiness status to PILOT_READY or REVIEW_REQUIRED.",
    whatEvidenceMatters: "Technical condition scores, regulatory clearances, active commitment status, and dependency logs.",
    whatHappensNext: "PILOT_READY solutions receive formal authorization for field pilot deployment.",
    whyThisStage: "Guarantees pilots are not authorized until all technical, regulatory, and institutional dependencies are satisfied.",
  },
  "/app/pilots": {
    route: "/app/pilots",
    stageName: "Field Pilot Execution & Monitoring",
    stageIndex: 7,
    totalStages: 7,
    description: "Milestone-based execution tracking of authorized field pilots in municipal target zones.",
    previousStage: "Pilot Readiness & Decision Assurance",
    nextStage: "Outcome Verification & Impact Audit",
    whoUsesIt: "Innovator Teams, HEI Leads, and Field Nodal Officers.",
    whatDecisionHappens: "Recording milestone completions (PROTOTYPE_DEPLOYED, FIELD_TESTED, MILESTONE_COMPLETED).",
    whatEvidenceMatters: "Field test logs, sensor telemetry, photographic evidence, and milestone sign-off sheets.",
    whatHappensNext: "Completed pilots submit final evidence for independent Outcome Verification.",
    whyThisStage: "Monitors operational execution in real field environments under municipal oversight.",
  },
  "/app/outcomes": {
    route: "/app/outcomes",
    stageName: "Outcome Verification & Impact Audit",
    stageIndex: 7,
    totalStages: 7,
    description: "Third-party audit and empirical verification of pilot outcome evidence.",
    previousStage: "Field Pilot Execution",
    nextStage: "Scaling & Policy Decision",
    whoUsesIt: "Independent Auditors, Government Leaders, and Evaluation Jury.",
    whatDecisionHappens: "Classifying evidence outcome as VALIDATED_IMPACT, INCONCLUSIVE, or REJECTED.",
    whatEvidenceMatters: "Empirical impact metrics, survey data, comparative baselines, and third-party audit reports.",
    whatHappensNext: "VALIDATED_IMPACT pilots qualify for state-wide scaling and policy adoption.",
    whyThisStage: "Maintains strict separation between operational pilot completion and proven outcome impact.",
  },
  "/app/challenges": {
    route: "/app/challenges",
    stageName: "Challenge Passport Registry",
    stageIndex: 1,
    totalStages: 7,
    description: "Registry of all societal challenge problem statements and standardized Challenge Passports.",
    previousStage: "Workspace Home",
    nextStage: "Problem Intake / Qualification",
    whoUsesIt: "All platform stakeholders.",
    whatDecisionHappens: "Browsing, searching, and inspecting challenge specifications and versions.",
    whatEvidenceMatters: "Passport JSON specifications, version history, evidence hashes, and problem boundaries.",
    whatHappensNext: "Inspect individual challenge passports or proceed to review/qualification.",
    whyThisStage: "Serves as the single source of truth for problem definitions across the platform.",
  },
  "/app/challenges/new": {
    route: "/app/challenges/new",
    stageName: "Challenge Submission Intake",
    stageIndex: 1,
    totalStages: 7,
    description: "Form interface for reporting new societal problem statements and attaching raw evidence.",
    previousStage: "Challenge Registry",
    nextStage: "Review Queue Intake",
    whoUsesIt: "Citizens, Innovators, and Field Officers.",
    whatDecisionHappens: "Drafting and submitting a formal challenge report.",
    whatEvidenceMatters: "Problem description, district, sector, target budget, and supporting files/photos.",
    whatHappensNext: "Submitted challenge enters the Government Review Queue.",
    whyThisStage: "Standardizes problem reporting at the point of intake to ensure data quality.",
  },
  "/app/organizations": {
    route: "/app/organizations",
    stageName: "Ecosystem Entity Governance",
    stageIndex: 0,
    totalStages: 7,
    description: "Management of government departments, HEI research institutions, and innovator organizations.",
    whoUsesIt: "Platform Administrators & Institutional Leads.",
    whatDecisionHappens: "Onboarding new entities and verifying organizational identity.",
    whatEvidenceMatters: "Registration numbers, institutional credentials, and primary contact details.",
    whatHappensNext: "Approved organizations can assign members and participate in matching.",
    whyThisStage: "Establishes secure, verified organizational boundaries across public sector stakeholders.",
  },
  "/app/admin/users": {
    route: "/app/admin/users",
    stageName: "User Access & Role Administration",
    stageIndex: 0,
    totalStages: 7,
    description: "RBAC administration for managing user accounts, platform roles, and nodal privileges.",
    whoUsesIt: "Platform Administrators.",
    whatDecisionHappens: "Granting or revoking user roles and organizational memberships.",
    whatEvidenceMatters: "User email, platform role assignments, and organizational memberships.",
    whatHappensNext: "Users execute actions within their authorized role boundaries.",
    whyThisStage: "Enforces principle-of-least-privilege security across all platform actions.",
  },
  "/app/admin/audit": {
    route: "/app/admin/audit",
    stageName: "System Security & Audit Trail",
    stageIndex: 0,
    totalStages: 7,
    description: "Immutable log of security events, session token mutations, and administrative overrides.",
    whoUsesIt: "Platform Administrators & Security Auditors.",
    whatDecisionHappens: "Reviewing security posture and investigating compliance events.",
    whatEvidenceMatters: "Audit log entries, timestamp hashes, actor IDs, and IP addresses.",
    whatHappensNext: "Exporting audit logs or taking corrective security measures.",
    whyThisStage: "Guarantees complete administrative auditability for public sector compliance.",
  },
  "/app/admin/ai": {
    route: "/app/admin/ai",
    stageName: "AI Operations & Audit Logs",
    stageIndex: 0,
    totalStages: 7,
    description: "Operational audit log of AI assistance requests, prompt hashes, and boundary compliance.",
    whoUsesIt: "Platform Administrators & AI Governance Officers.",
    whatDecisionHappens: "Auditing AI model performance and verifying non-authoritative boundary compliance.",
    whatEvidenceMatters: "Prompt hashes, model latency, token usage, and `is_ai_advisory: true` flags.",
    whatHappensNext: "Tuning prompt parameters or verifying safety boundaries.",
    whyThisStage: "Ensures AI operates strictly as an advisory assistant with zero autonomous decision power.",
  },
  "/app/evaluation": {
    route: "/app/evaluation",
    stageName: "Jury Evaluation & Architecture Workspace",
    stageIndex: 0,
    totalStages: 7,
    description: "Dedicated workspace for SIH jury members to evaluate NIRNAY's core architectural principles and live scenarios.",
    whoUsesIt: "SIH Evaluation Jury & Technical Reviewers.",
    whatDecisionHappens: "Evaluating governance compliance, dependency invalidation, and Decision Assurance.",
    whatEvidenceMatters: "Synthetic scenario states, audit receipts, AI boundary toggles, and proof panel data.",
    whatHappensNext: "Completing jury evaluation scoring and verification.",
    whyThisStage: "Provides a controlled environment to verify all architectural invariants without altering real data.",
  },
};
