import { GuidanceJourney } from "./types";

export const ROLE_JOURNEYS: Record<string, GuidanceJourney> = {
  "citizen-journey": {
    id: "citizen-journey",
    roleGroup: "CITIZEN_INNOVATOR",
    title: "Innovator & Citizen Workflow",
    description: "Learn how to report societal challenges, attach field evidence, track passports, and monitor status.",
    steps: [
      {
        id: "citizen-1",
        title: "Workspace Overview & Metrics",
        description: "Your home dashboard provides immediate visibility into your submitted challenges, active statuses, and platform notifications.",
        whyItMatters: "Maintains full transparency across your innovation and societal problem tracking.",
        route: "/app",
        targetSelector: '[data-tour="dashboard-nav"]',
        position: "bottom",
      },
      {
        id: "citizen-2",
        title: "Submit Societal Challenge",
        description: "Report real municipal or regional problem statements with structured domain tags, sector constraints, and location details.",
        whyItMatters: "Ensures civic problem claims are formally structured before entering government evaluation.",
        route: "/app/challenges/new",
        targetSelector: '[data-tour="report-challenge-nav"]',
        position: "bottom",
      },
      {
        id: "citizen-3",
        title: "Attach Verifiable Evidence",
        description: "Upload field photos, survey data, or official documents to back your challenge report.",
        whyItMatters: "Raw problem claims require factual grounding evidence before nodal officers can proceed with qualification.",
        route: "/app/challenges/new",
        targetSelector: '[data-tour="evidence-section"]',
        position: "top",
      },
      {
        id: "citizen-4",
        title: "Standardized Challenge Passport",
        description: "Inspect the generated immutable Challenge Passport containing version history, evidence hashes, and problem boundaries.",
        whyItMatters: "Prevents scope creep and guarantees clear, unambiguous problem specifications.",
        route: "/app/challenges",
        targetSelector: '[data-tour="challenges-list"]',
        position: "top",
      },
      {
        id: "citizen-5",
        title: "Track Lifecycle Progress",
        description: "Follow your challenge from initial triaging, qualification, HEI capability matching, up to pilot deployment and outcome audit.",
        whyItMatters: "Eliminates black-box delays by providing real-time visibility at every governance transition.",
        route: "/app/challenges",
        targetSelector: '[data-tour="status-tracking"]',
        position: "top",
      },
    ],
  },
  "government-journey": {
    id: "government-journey",
    roleGroup: "GOVERNMENT_NODAL",
    title: "Government Nodal Officer Workflow",
    description: "Guide through review queue, problem qualification, HEI matching, pilot readiness, and Decision Assurance.",
    steps: [
      {
        id: "gov-1",
        title: "Review Queue & Intake",
        description: "Access incoming societal challenge reports submitted by citizens, departments, and regional partners.",
        whyItMatters: "Prevents municipal backlogs and ensures rapid triaging of urgent public issues.",
        route: "/app/review",
        targetSelector: '[data-tour="review-queue-nav"]',
        position: "bottom",
      },
      {
        id: "gov-2",
        title: "Qualify Problem Route",
        description: "Categorize challenges into SERVICE, CLARIFY, RESEARCH_REVIEW, or INNOVATION_CHALLENGE. AI may suggest the route, but human nodal officers authorize the binding decision.",
        whyItMatters: "Not every societal complaint should consume innovation resources. Routine municipal complaints belong in SERVICE or CLARIFY.",
        route: "/app/qualification",
        targetSelector: '[data-tour="qualification-nav"]',
        position: "bottom",
      },
      {
        id: "gov-3",
        title: "Challenge Passport & Evidence Review",
        description: "Verify uploaded evidence metrics, location bounds, and underlying problem facts before matching.",
        whyItMatters: "Decisions must be backed by verifiable evidence, not arbitrary opinion.",
        route: "/app/challenges",
        targetSelector: '[data-tour="passport-evidence"]',
        position: "top",
      },
      {
        id: "gov-4",
        title: "HEI Capability Matching",
        description: "Utilize algorithmic matching to connect qualified innovation challenges with university labs and academic research units.",
        whyItMatters: "Connects field challenges directly with verified academic research capabilities.",
        route: "/app/hei-matching",
        targetSelector: '[data-tour="hei-matching-nav"]',
        position: "bottom",
      },
      {
        id: "gov-5",
        title: "Pilot Readiness & Dependency Audit",
        description: "Evaluate multi-dimensional readiness across technical, regulatory, financial, and operational criteria.",
        whyItMatters: "All underlying institutional commitments must be active before authorizing field deployment.",
        route: "/app/readiness",
        targetSelector: '[data-tour="readiness-nav"]',
        position: "bottom",
      },
      {
        id: "gov-6",
        title: "Decision Assurance & Immutable Receipts",
        description: "Inspect WhyThisState badges and cryptographic audit receipts generated for every transition.",
        whyItMatters: "Guarantees public accountability and complete auditability for government stakeholders.",
        route: "/app/readiness",
        targetSelector: '[data-tour="decision-assurance"]',
        position: "top",
      },
    ],
  },
  "hei-journey": {
    id: "hei-journey",
    roleGroup: "HEI",
    title: "HEI & Academic Lead Workflow",
    description: "Understand matching opportunities, institutional commitments, readiness conditions, and outcome evidence.",
    steps: [
      {
        id: "hei-1",
        title: "Explore Matched Opportunities",
        description: "Review qualified societal challenges matched to your institution's research labs and domain expertise.",
        whyItMatters: "Facilitates targeted university-government collaboration on high-impact public challenges.",
        route: "/app/hei-matching",
        targetSelector: '[data-tour="hei-opportunities"]',
        position: "top",
      },
      {
        id: "hei-2",
        title: "Issue Formal Institutional Commitment",
        description: "Submit binding institutional commitment agreements specifying lab resources, faculty leads, and budget allocations.",
        whyItMatters: "Establishes formal academic responsibility. Note: matching is advisory, commitment is binding.",
        route: "/app/commitments",
        targetSelector: '[data-tour="commitments-nav"]',
        position: "bottom",
      },
      {
        id: "hei-3",
        title: "Satisfy Readiness Conditions",
        description: "Work through technical, regulatory, and safety prerequisites required before pilot rollout.",
        whyItMatters: "Satisfying all conditions unlocks formal PILOT_READY authorization.",
        route: "/app/readiness",
        targetSelector: '[data-tour="readiness-conditions"]',
        position: "top",
      },
      {
        id: "hei-4",
        title: "Execute Field Deployment",
        description: "Deploy milestone-based pilots in designated municipal or field target areas.",
        whyItMatters: "Moves research prototypes out of the lab into real municipal operational environments.",
        route: "/app/pilots",
        targetSelector: '[data-tour="pilots-nav"]',
        position: "bottom",
      },
      {
        id: "hei-5",
        title: "Submit Outcome Evidence",
        description: "Upload empirical performance metrics, survey data, and audit records to verify impact.",
        whyItMatters: "Proves real-world outcome separate from simple operational completion.",
        route: "/app/outcomes",
        targetSelector: '[data-tour="outcomes-nav"]',
        position: "bottom",
      },
    ],
  },
  "admin-journey": {
    id: "admin-journey",
    roleGroup: "ADMIN",
    title: "Platform Administration & Governance",
    description: "Manage ecosystem entities, user roles, security audit trails, and AI governance logs.",
    steps: [
      {
        id: "admin-1",
        title: "Organization Registry",
        description: "View and onboard government departments, HEI research institutions, and innovator entities.",
        whyItMatters: "Ensures trusted organizational identity boundaries across the entire civic platform.",
        route: "/app/organizations",
        targetSelector: '[data-tour="organizations-nav"]',
        position: "bottom",
      },
      {
        id: "admin-2",
        title: "User Access & Role Management",
        description: "Assign platform roles (Platform Admin, Nodal Officer, HEI Lead, Innovator) and manage user permissions.",
        whyItMatters: "Enforces strict RBAC and principle-of-least-privilege for public sector operations.",
        route: "/app/admin/users",
        targetSelector: '[data-tour="users-nav"]',
        position: "bottom",
      },
      {
        id: "admin-3",
        title: "System Security & Audit Trail",
        description: "Inspect immutable security audit logs tracking authentication events, session tokens, and role mutations.",
        whyItMatters: "Provides full transparency for compliance and security auditing.",
        route: "/app/admin/audit",
        targetSelector: '[data-tour="audit-nav"]',
        position: "bottom",
      },
      {
        id: "admin-4",
        title: "AI Operations & Audit Logs",
        description: "Monitor AI assistance calls, prompt hashes, response latencies, and non-authoritative boundary compliance.",
        whyItMatters: "Guarantees AI remains strictly advisory (`is_ai_advisory: true`) with zero autonomous authority.",
        route: "/app/admin/ai",
        targetSelector: '[data-tour="ai-nav"]',
        position: "bottom",
      },
    ],
  },
  "jury-90sec-journey": {
    id: "jury-90sec-journey",
    roleGroup: "EVALUATION_JURY",
    title: "90-Second Jury Architecture Tour",
    description: "An accelerated guided walk-through demonstrating NIRNAY's core architectural principles and governance invariants.",
    steps: [
      {
        id: "jury-1",
        title: "1. Problem Qualification Protocol",
        description: "NIRNAY forces unstructured problem statements into 4 distinct routes (SERVICE, CLARIFY, RESEARCH_REVIEW, INNOVATION_CHALLENGE). AI proposes suggestions, but human nodal officers hold binding decision authority.",
        whyItMatters: "Prevents wasteful innovation spending on routine municipal complaints.",
        route: "/app/qualification",
        targetSelector: '[data-tour="qualification-nav"]',
        position: "bottom",
      },
      {
        id: "jury-2",
        title: "2. Standardized Challenge Passport",
        description: "Every qualified challenge receives an immutable Challenge Passport with version tracking, evidence hashes, and defined boundary metrics.",
        whyItMatters: "Guarantees problem baseline clarity across academic, government, and industry actors.",
        route: "/app/challenges",
        targetSelector: '[data-tour="passport-section"]',
        position: "top",
      },
      {
        id: "jury-3",
        title: "3. Decision Assurance Engine",
        description: "Review WhyThisState rationale badges and cryptographic decision receipts generated automatically at every governance state transition.",
        whyItMatters: "Verifiable, tamper-evident proof of governance compliance.",
        route: "/app/readiness",
        targetSelector: '[data-tour="decision-assurance"]',
        position: "top",
      },
      {
        id: "jury-4",
        title: "4. Dependency-Aware Pilot Readiness",
        description: "Pilot readiness requires satisfied technical conditions AND active institutional commitments. A pilot cannot become PILOT_READY without active commitments.",
        whyItMatters: "Prevents premature field deployment without verified backing.",
        route: "/app/readiness",
        targetSelector: '[data-tour="readiness-dependencies"]',
        position: "top",
      },
      {
        id: "jury-5",
        title: "5. Automatic Dependency Invalidation",
        description: "If an underlying institutional commitment is withdrawn, NIRNAY preserves historical audit logs but automatically invalidates readiness (PILOT_READY ➔ REVIEW_REQUIRED).",
        whyItMatters: "Real-world readiness dynamically reflects current dependency integrity.",
        route: "/app/readiness",
        targetSelector: '[data-tour="readiness-invalidation"]',
        position: "top",
      },
      {
        id: "jury-6",
        title: "6. Operational COMPLETED ≠ Proven Impact",
        description: "Inspect pilots marked COMPLETED with INCONCLUSIVE outcome evidence conclusions. Completing field milestones is strictly separated from proving measurable outcome.",
        whyItMatters: "Prevents false success reporting in public sector evaluations.",
        route: "/app/outcomes",
        targetSelector: '[data-tour="outcomes-section"]',
        position: "top",
      },
      {
        id: "jury-7",
        title: "7. Non-Authoritative AI Boundary",
        description: "Review AI audit trails confirming AI only structures and suggests, while deterministic rules constrain and human actors authorize.",
        whyItMatters: "AI proposes → Rules constrain → Evidence supports → Human authorizes.",
        route: "/app/evaluation",
        targetSelector: '[data-tour="ai-boundary-section"]',
        position: "top",
      },
    ],
  },
};
