from enum import Enum


class QualificationRoute(str, Enum):
    SERVICE = "SERVICE"
    CLARIFY = "CLARIFY"
    RESEARCH_REVIEW = "RESEARCH_REVIEW"
    INNOVATION_CHALLENGE = "INNOVATION_CHALLENGE"


class CommitmentStatus(str, Enum):
    PROPOSED = "PROPOSED"
    OFFERED = "OFFERED"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    WITHDRAWN = "WITHDRAWN"
    EXPIRED = "EXPIRED"


class ConditionStatus(str, Enum):
    SATISFIED = "SATISFIED"
    UNSATISFIED = "UNSATISFIED"
    UNKNOWN = "UNKNOWN"
    DISPUTED = "DISPUTED"
    EXPIRED = "EXPIRED"


class ReadinessStatus(str, Enum):
    BLOCKED = "BLOCKED"
    REVIEW_READY = "REVIEW_READY"
    PILOT_READY = "PILOT_READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class OperationalStatus(str, Enum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"


class EvidenceConclusion(str, Enum):
    NOT_REVIEWED = "NOT_REVIEWED"
    VALIDATED = "VALIDATED"
    ITERATE = "ITERATE"
    INCONCLUSIVE = "INCONCLUSIVE"


class PlatformRole(str, Enum):
    COMMUNITY_REPORTER = "COMMUNITY_REPORTER"
    GOVERNMENT_REVIEWER = "GOVERNMENT_REVIEWER"
    GOVERNMENT_ADMIN = "GOVERNMENT_ADMIN"
    HEI_MEMBER = "HEI_MEMBER"
    HEI_REVIEWER = "HEI_REVIEWER"
    HEI_ADMIN = "HEI_ADMIN"
    INDUSTRY_MEMBER = "INDUSTRY_MEMBER"
    INDUSTRY_ADMIN = "INDUSTRY_ADMIN"
    PLATFORM_ADMIN = "PLATFORM_ADMIN"


class OrganizationType(str, Enum):
    GOVERNMENT = "GOVERNMENT"
    HEI = "HEI"
    INDUSTRY = "INDUSTRY"
    MSME = "MSME"
    RESEARCH_ORGANIZATION = "RESEARCH_ORGANIZATION"
    CIVIL_SOCIETY = "CIVIL_SOCIETY"
    COMMUNITY = "COMMUNITY"


class OrganizationStatus(str, Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"


class SecurityAuditEventType(str, Enum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET = "PASSWORD_RESET"
    SESSION_REVOKED = "SESSION_REVOKED"
    EMAIL_VERIFIED = "EMAIL_VERIFIED"
    MEMBERSHIP_ROLE_CHANGED = "MEMBERSHIP_ROLE_CHANGED"
    ORGANIZATION_STATUS_CHANGED = "ORGANIZATION_STATUS_CHANGED"
